name: Trigger auto deployment for visualscriptingpython

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/visualscriptingpython-AutoDeployTrigger-614b1f84-5c18-4320-aa68-c21e2a7d5e24.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.VISUALSCRIPTINGPYTHON_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VISUALSCRIPTINGPYTHON_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VISUALSCRIPTINGPYTHON_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: uninorte.azurecr.io
          registryUsername: ${{ secrets.VISUALSCRIPTINGPYTHON_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VISUALSCRIPTINGPYTHON_REGISTRY_PASSWORD }}
          containerAppName: visualscriptingpython
          resourceGroup: proyectosIngSistemas_group
          imageToBuild: uninorte.azurecr.io/visualscriptingpython:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


